### ISSUE TITLE
实际应用中的问题

### ISSUE THREAD

**Issue by slodier** [zhouxing5311/ZZCircleProgress#1]
测试发现,实际下载在主线程 _circle3.progress = progress; 发现不断重绘,十分诡异.

**Comment by zhouxing5311** [comment]
你好，重绘UI界面是要在主线程。能问一下出问题的具体使用场景吗？或者有没有demo我查看修复一下。也可以加我扣扣1098660224互相学习沟通一下，谢谢😊
