### ISSUE TITLE
初始化方法中设置的fill颜色无效

### ISSUE THREAD

**Issue by myDonghao** [zhouxing5311/ZZCircleProgress#10]
我将demo 中的
- (void)addProgressViewByAutoLayout；中的初始化方法修改为：
self.progressView = [[ZZCircleProgress alloc] initWithFrame:CGRectZero pathBackColor:[UIColor grayColor] pathFillColor:[UIColor greenColor] startAngle:0 strokeWidth:2];

然后将随机填充色给注释掉，之后除非重新设置另一个颜色，否则一直是默认的红色。

**Comment by zhouxing5311** [comment]
@myDonghao 感谢建议，是initsubviews方法提前调用了，设置颜色的时候没走set方法，导致颜色设置失效。已发布0.3.1修复版本。
