### ISSUE TITLE
圆点没有动画？？

### ISSUE THREAD

**Issue by hanmaochan** [zhouxing5311/ZZCircleProgress#12]
在Demo中，正常，添加到项目中，圆点图片动画就不生效了。CAKeyframeAnimation 设置为values时就有动画，设path时就没有动画效果。应该是首项目的影响，但是不知具体什么原因

**Comment by zhouxing5311** [comment]
@hanmaochan 我这边暂时没遇到这种情况。排查下项目中有没有hook CAAnimation相关方法。
