### ISSUE TITLE
在swift 上 使用autolayout 无效

### ISSUE THREAD

**Issue by thomas-cao** [zhouxing5311/ZZCircleProgress#13]
我在xib中拖进一个UIVIew 把view的class设置为 ZZCircleProgress  但是显示出来是有问题的，当我初始化的时候直接设置frame 就没有这个问题

**Comment by zhouxing5311** [comment]
@xiaocaoge 是UITableViewCell的xib吗？显示有问题具体是哪里的问题。有没有效果图或示例代码。
