### ISSUE TITLE
填充的颜色可以设置为渐变颜色吗？例如：从开的浅蓝色到深蓝色

### ISSUE THREAD

**Issue by MrGaoHe** [zhouxing5311/ZZCircleProgress#15]

**Comment by zhouxing5311** [comment]
![image](https://user-images.githubusercontent.com/14874355/68284275-21d7e180-00b8-11ea-9f78-32f8ed0730b0.png)
https://github.com/zhouxing5311/ZZGradientProgress
看下这个
