### ISSUE TITLE
怎样关闭加载动画？

### ISSUE THREAD

**Issue by beilusen** [zhouxing5311/ZZCircleProgress#19]
怎样关闭加载动画？

**Comment by zhouxing5311** [comment]
duration设置为0

**Comment by mlp1995** [comment]
设置为0 也会有一个很快的加载动画

**Comment by zhouxing5311** [comment]
`
[CATransaction begin];
[CATransaction setDisableActions:YES];
 
// 执行动画
xxx

[CATransaction commit];
`
关闭隐式动画试一下
@mlp1995

**Comment by mlp1995** [comment]
好的谢谢 👌
