### ISSUE TITLE
当用Xib 放在Cell 上时，无法显示！

### ISSUE THREAD

**Issue by LassZhang** [zhouxing5311/ZZCircleProgress#2]
![image](https://user-images.githubusercontent.com/16604166/29857791-ffb3b250-8d8c-11e7-9dc5-6fb2629783cd.png)
![image](https://user-images.githubusercontent.com/16604166/29857819-20506d1e-8d8d-11e7-9bce-1d2b27a568b6.png)

**Comment by LassZhang** [comment]
用Xib拖一个控件，class 设置为ZZCircleProgress ,然后再Cell.m 中更新进度，不知道为啥，不能显示

**Comment by zhouxing5311** [comment]
拉一下最新代码，已经解决。习惯了纯代码写界面，没有加入awakeFromNib，所以xib导入的时候没有正确初始化导致出现问题。
