### ISSUE TITLE
急急急 晚上上线!!!  请问 起点和重点 怎么去掉圆角???

### ISSUE THREAD

**Issue by ke112** [zhouxing5311/ZZCircleProgress#22]
起点和重点 怎么修改可以去掉 圆角 蜕化效果???

**Comment by zhouxing5311** [comment]
_backLayer.lineCap = @"round";
_progressLayer.lineCap = @"round";
这两行代码注释掉，这个是设置端点样式的

**Comment by ke112** [comment]
谢谢老板,祝老板发大财!!!!   (#^.^#)
