### ISSUE TITLE
进度条 走完后  怎么设置回调 或者通知呢？

### ISSUE THREAD

**Issue by LaoYao121** [zhouxing5311/ZZCircleProgress#23]
我这边有个需求  进度条 走完要处理其他逻辑  查看你这边代码 没发现 这个完成后的 回调或者通知  请问怎么监听呢？望回复谢谢！！

**Comment by zhouxing5311** [comment]
> 我这边有个需求 进度条 走完要处理其他逻辑 查看你这边代码 没发现 这个完成后的 回调或者通知 请问怎么监听呢？望回复谢谢！！

动画时长是自己可以设置的，你可以使用dispatch_after计时器或NSTimer，延迟对应的时间后做自己的业务逻辑
