### ISSUE TITLE
UICollectionView  + ZZCircleProgress使用时 每次圆点刷新后回到起始点

### ISSUE THREAD

**Issue by kinghour** [zhouxing5311/ZZCircleProgress#3]
你好  我将ZZCACircleProgress嵌进UICollectionViewCell里面  总共5个items  每次刷新到第三个的时候  pointImage只停留在起始点的位置  设置动画停留在终点也不器左右  请问应该从哪方面着手更改好点？？

**Comment by zhouxing5311** [comment]
你还是提供个demo我帮你看下吧，看你这么描述不清楚哪里的问题。

**Comment by kinghour** [comment]
好 这个问题困惑我好几天了
容量有点大  30MB  怎么发给你？

**Comment by zhouxing5311** [comment]
百度云，github什么的都可以。

**Comment by kinghour** [comment]
https://pan.baidu.com/s/1eSyDdTK

**Comment by kinghour** [comment]
进入到设备首页  点击下方tableViewcell任意一个进去
![snip20171207_1](https://user-images.githubusercontent.com/18476012/33705457-521c6a56-db6b-11e7-9544-7eb200c8a0df.png)
![snip20171207_2](https://user-images.githubusercontent.com/18476012/33705489-7ceda33a-db6b-11e7-820f-0ea1fe679375.png)

**Comment by kinghour** [comment]
谢谢了

**Comment by kinghour** [comment]
找到原因了  在图层添加动画的时候  有个参数为空了  (ZZCACircleProgress -> .m文件  ->  272行)
![snip20171207_3](https://user-images.githubusercontent.com/18476012/33707967-203df8ca-db74-11e7-9bf6-945d088e857a.png)

**Comment by zhouxing5311** [comment]
看了半天发现参数都对，确实是小圆点动画没能触发。你说的是那个参数为空？打了断点都是有值的，就是那个可有可无的forKey是空的。还有就是你那个动画触发时机不太对，应该是cell停止滑动再刷新正在显示的进度。
